(function () {
  'use strict';
  /**
   * config
   * @type {[type]}
   */
  angular
    .module(APP_NAME)
    .config(config);

  /**
   * [config description]
   * @method config
   * @param  {[type]} $stateProvider           [description]
   * @param  {[type]} $urlRouterProvider       [description]
   * @param  {[type]} tmhDynamicLocaleProvider [description]
   * @param  {[type]} bvBreakpointsService       [description]
   * @param  {[type]} $translateProvider       [description]
   * @param  {[type]} $httpProvider            [description]
   * @return {[type]}                          [description]
   */
  function config(tmhDynamicLocaleProvider, $translateProvider, $translatePartialLoaderProvider, $httpProvider, $urlRouterProvider, $locationProvider, $compileProvider, CUSTOMIZE, DEBUG_MODE) {

    if (!DEBUG_MODE) {
      $compileProvider.debugInfoEnabled(false); // disables AngularJS debug info
    };

    if (DEBUG_MODE) {
      $translateProvider.useMissingTranslationHandlerLog(); // warns about missing translates
    }

    // per traduzioni

    $translateProvider.useStaticFilesLoader({
      prefix: 'assets/autogenerated/i18n/',
      suffix: '.json'
    });

    $translateProvider.useSanitizeValueStrategy('escapeParameters');
    $translateProvider.preferredLanguage(CUSTOMIZE.LOCALES.preferredLocale);
    $translateProvider.useLocalStorage();

    // per locale angularjs
    tmhDynamicLocaleProvider.localeLocationPattern('bower_components/angular-i18n/angular-locale_{{locale}}.js');

    // default state
    $urlRouterProvider.otherwise('/home');

    // GLOBAL HANDLING HTTP
    $httpProvider.interceptors.push('bvHttpInterceptor');

    // per evitare la cache delle chiamate REST
    $httpProvider.defaults.headers.common["Cache-Control"] = "no-cache";
    $httpProvider.defaults.headers.common.Pragma = "no-cache";
    $httpProvider.defaults.headers.common["If-Modified-Since"] = "0";
    $httpProvider.defaults.useXDomain = true;
    $httpProvider.defaults.headers.common = 'Content-Type: application/json';
    $httpProvider.defaults.withCredentials = true;

  }

}());